name: Google Java Format

on: [ push, pull_request ]

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3.6.0
        with:
          args: "--skip-sorting-imports --replace"
          # Recommended if you use MacOS:
          github-token: ${{ secrets.GITHUB_TOKEN }}
